loki:
  image:
    tag: 2.9.6
  persistence:
    enabled: true
    storageClassName: standard
    size: 1Gi
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  config:
    limits_config:
      retention_period: 12h
    common:
      ring:
        kvstore:
          store: inmemory
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
promtail:
  enabled: false

grafana:
  enabled: false
  sidecar:
    datasources:
      enabled: false

loki-stack:
  grafana:
    sidecar:
      datasources:
        enabled: false
