apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rabbitmq-netpol
  namespace: platform
spec:
  podSelector:
    matchLabels:
      app: rabbitmq
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: backend
        - podSelector:
            matchLabels:
              app: notification-service
      ports:
        - protocol: TCP
          port: 5672
        - protocol: TCP
          port: 15672  # management UI, for your own kubectl port-forward access
    - ports:
        - protocol: TCP
          port: 15672
